# Generated by Django 5.2.1 on 2025-06-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='created_by',
        ),
    ]
